### ISSUE TITLE
Hiccup.div conflicts with Base.div

### ISSUE THREAD

**Issue by TotalVerb** [JunoLab/Hiccup.jl#10]
`div` is an export of Hiccup.jl, but is also a part of Base. In newer versions of Julia this export is not useful because it is shadowed by `Base.div`, and the result is that neither `Base.div` nor `Hiccup.div` can be used unqualified. Probably the best solution is to export `div` under a different name.

**Comment by MikeInnes** [comment]
Do you think `hdiv` would work as a new name?

**Comment by TotalVerb** [comment]
It would work, but it'd be inconsistent with everything else, so it's hard to say. Unfortunately, `div` is a common enough tag that `Hiccup.div` be an inconvenience to write.
