### ISSUE TITLE
th, colgroup (table tags) should be exported

### ISSUE THREAD

**Issue by JeffreySarnoff** [JunoLab/Hiccup.jl#20]
Please export `th` and `colgroup` ; other table tags are `caption`, `col`, `thead`, `tbody`, `tfoot`.

**Comment by TotalVerb** [comment]
I don't like exporting tags. It's easy enough to call `@tags` on the ones used, right?

**Comment by JeffreySarnoff** [comment]
I had presumed that whatever the reason some tags were exported would be reason to export these.  If the package works just the same with @tags from the outside -- it does not matter.   Looking at [HTML5](https://www.w3.org/TR/html5/tabular-data.html#the-thead-element), their example uses thead and tbody as an odd kind of tag, one that has (or is not required to have) no closing </tag>.  That is not valid XML, so not valid for use in XHTML docs.  I have not looked into it more than to have seen their example.

**Comment by JeffreySarnoff** [comment]
> Tag omission in text/html:  A thead element's end tag can be omitted if the thead element is immediately followed by a tbody or tfoot element.
> As that means closing the tag works (and is better practice) -- I am closing this.
