### ISSUE TITLE
Hiccup produces a set of warnings on Julia 0.4 - tag a new version?

### ISSUE THREAD

**Issue by maximsch2** [JunoLab/Hiccup.jl#8]
Maybe it is time to tag a new version so that new users on Julia 0.4 have better out-of-box experience? All those warnings are already fixed on master.

**Comment by catawbasam** [comment]
bump

**Comment by TotalVerb** [comment]
I think this issue can be closed now that 0.0.2 was tagged.

**Comment by maximsch2** [comment]
Can confirm that it doesn't spew warnings any more
